# Generated by Django 5.2 on 2026-03-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture_width',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
