# Generated by Django 5.2 on 2026-03-29 22:32

import pictures.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django2', '0002_product_picture_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=pictures.models.PictureField(aspect_ratios=[None], breakpoints={'l': 1200, 'm': 992, 's': 768, 'xl': 1400, 'xs': 576}, container_width=1200, file_types=['AVIF'], grid_columns=5, height_field='picture_height', pixel_densities=[1], upload_to='products/', width_field='picture_width'),
        ),
    ]
